### ISSUE TITLE
block spam from cloyne.org listserv

### ISSUE THREAD

**Issue by sunnysideofthescreen** [cloyne/network#105]
there has been pretty obscene and unwanted emails to various cloyne.org listservs. see my spam box below:

<img width="920" alt="screen shot 2017-02-26 at 4 58 06 pm" src="https://cloud.githubusercontent.com/assets/15096867/23345615/cf6a0820-fc45-11e6-9e87-5d75cbab988d.png">
<img width="920" alt="screen shot 2017-02-26 at 4 58 20 pm" src="https://cloud.githubusercontent.com/assets/15096867/23345616/d0c8a1f4-fc45-11e6-9543-72cc55f802eb.png">
<img width="918" alt="screen shot 2017-02-26 at 4 58 30 pm" src="https://cloud.githubusercontent.com/assets/15096867/23345617/d31aa4b6-fc45-11e6-906a-26ef2ccb2c65.png">

**Comment by jmrtns** [comment]
One issue is that a message was approved once and now spam bots know that it's a valid list. besides that, there's not much we can do but blacklist email addresses. These messages are not going through though, they are asking for moderation and the unmoderated messages are being sent to spam by google. The messages can be ignored if they're in your spam folder or marked as spam if they go to you're inbox. Mostly it's just a matter of ignoring it

**Comment by sunnysideofthescreen** [comment]
these are going to my board rep email, but they go straight to my inbox (at least when i use apple mail). it is hard for me to ignore them since i am one of the few managers that actually moderate emails on our listserv, so i like to open all sympa emails. 

please blacklist the emails that have been sending them thus far. you might have different reactions, but I find it particularly repulsive opening emails only to find cartoon nudes...

**Comment by jmrtns** [comment]
I'm not undermining how disturbing it is but there's also not much that I
can do, there are so many emails sending spam that we can't really
moderate/blacklist it on our own. Maybe there are some established
blacklist that we could import and I'll look into that but even then alot
are still going to slip through.  Usually just the email from address and
the subject are enough information to moderate it, if you have any doubts
about a particular email then let someone else moderate it. I wish I could
give better advice / do more than say ignore it but that's how spam works,
when the spammer's email gets blacklisted, they just use a new email.

On Feb 27, 2017 06:43, "kelly archer" <notifications@github.com> wrote:

these are going to my board rep email, but they go straight to my inbox (at
least when i use apple mail). it is hard for me to ignore them since i am
one of the few managers that actually moderate emails on our listserv, so i
like to open all sympa emails.

please blacklist the emails that have been sending them thus far. you might
have different reactions, but I find it particularly repulsive opening
emails only to find cartoon nudes...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cloyne/network/issues/105#issuecomment-282739153>, or mute
the thread

**Comment by mitar** [comment]
So it seems sender e-mails are changing all the time. Is there anything which is not changing? Is there any text snippet which is the same in all e-mails?

One solution could be that any e-mail which is coming from an address (`@outlook.com` OR `@sbcglobal.net`) AND is not subscribed to a target mailing list, is automatically dropped.

**Comment by mitar** [comment]
So I configured `*@sbcglobal.net` to be blacklisted on the following mailing lists/files:

```
/srv/sympa/data/list_data/hack-news/search_filters/blacklist.txt
/srv/sympa/data/list_data/clones.2015s/search_filters/blacklist.txt
/srv/sympa/data/list_data/alumni/search_filters/blacklist.txt
/srv/sympa/data/list_data/clones/search_filters/blacklist.txt
```

Those will be [quietly rejected automatically](https://www.sympa.org/manual/authorization-scenarios#blacklist_implicit_rule).

For `outlook.com` we could do something similar, but the no sender to the mailing list can be from there.

Alternatively, we can define a [custom more complicated scenario](https://www.sympa.org/manual/authorization-scenarios#custom_perl_package_conditions).

Or, if we find any fixed string in body, we can filter based on that. Or is there something fixed in subjects?

**Comment by sunnysideofthescreen** [comment]
thanks for doing something about this, i appreciate it. let’s hope this helps!

**Comment by jmrtns** [comment]
http://spamassassin.apache.org/

I'll look into this a bit more.  Blocking sbcglobal by domain is probably
fine because it's such a niche email provider but Outlook is harder since
actual members send to the list from different emails, including ones not
registered, and apparently a few people use Outlook.

Another interesting thing is that some of these messages get caught by
Gmail spam filters in some manager accounts but not others. Also some
managers spam filters just catch all sympa moderation requests, even actual
ones

**Comment by mitar** [comment]
We do not need a spam assassin. We do not want to be in the place where we want to do our own spam filtering (what about false positives?). Because for now e-mails seems to follow some patterns, we can just hard-code to them.

**Comment by mitar** [comment]
So what is the state of this? How much spam is coming?

**Comment by sunnysideofthescreen** [comment]
a couple a day, sometimes more. 

one old member definitely has a phished email account, she sends a lot: donyayazdi@yahoo.com <mailto:donyayazdi@yahoo.com>. maybe we can permanently block that account?

**Comment by mitar** [comment]
> a couple a day, sometimes more. 

Are they of the same kind? Like same sender? Like we saw before? That could be easier to filter.

> one old member definitely has a phished email account, she sends a lot: donyayazdi@yahoo.com <mailto:donyayazdi@yahoo.com>. maybe we can permanently block that account?

That is probably fake anyway, it is not necessary that she was hacked. But yes, we could just limit any e-mail saying that it is from this address.

**Comment by sunnysideofthescreen** [comment]
Are the of the same kind? Not verbatim, but they are all generally along the lines of promoting viagra (or something of the like) or prostitution-type deals. 

Truly,
Kelly

**Comment by mitar** [comment]
With "kind" I was more asking if there is some simple pattern to it. Like the one you observed for `donyayazdi@yahoo.com`. Does those other have some pattern like that?

**Comment by sunnysideofthescreen** [comment]
hmmm not sure. can you take a look yourself? :)

**Comment by mitar** [comment]
I think I will leave to the network manager to do so. ;-)
