### ISSUE TITLE
eduroam/airbears2 on our APs

### ISSUE THREAD

**Issue by jmrtns** [cloyne/network#66]
Is it possible, after connecting to Cory, to have eduroam/airbears on our aps to have non vpn access to on campus services like the library, it could also be a means of faster internet. If people log into their own air-bears account then I doubt they will torrent, etc. it might also be more inviting to professors and make us seem more "official"?

**Comment by mitar** [comment]
No, we do not have a way to connect to the Eduroam/Airbears. We could discuss this with somebody on campus (I do not know who), but things just do not work like that. Networks are not just magically "combined" just because they are next to each other. And it would not mean faster Internet.

**Comment by mitar** [comment]
But what we could do is simply bridge the house to AirBears network with wireless. Hmm.

This could be doable. So with an extra antenna we connect to AirBears, bridge the network, and then deploy that network as an extra SSID to us, our network serving just as bridge, so no logic and nothing, for AirBears.

I am not sure if we really want to do that. But we could. We could also spread CalVisitor and people could use that for our visitors.

**Comment by mitar** [comment]
Bring this to council. :-) But it is highly experimental idea. :-)

**Comment by jmrtns** [comment]
Would it require better APs than the UniFis ones we currently have? I also
don't understand how we would be able to bridge since I know nothing about
WPA2 enterprise

**Comment by mitar** [comment]
No, APs should be good.

Yes, it would require quite some research and engineering effort to make it work, probably.

**Comment by mitar** [comment]
After some more thinking and researching, I think this is not really doable. So I would suggest to pull this off from the council agenda and until somebody makes first proof of concept working prototype we do not bring this to the house.

You can bring to the house if you would like that house officially get into the contact with university so that they would officially deploy the network here. Or, if we would like to officially become part of the Eduroam federation (but that would be a lot of paperwork and work as well, it would not give us any paper access though).
